smagg:
  outputs:

    dev:
      type: postgres
      threads: 8
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      dbname: metro
      schema: public

  target: dev
